# Generated by Django 4.1.7 on 2023-04-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_enrollmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='advisor',
        ),
    ]
