# Generated by Django 4.1.7 on 2023-04-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_enrollmentrequest_advisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentRequest',
        ),
    ]
