# Generated by Django 4.1.7 on 2023-03-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sector',
            table='Sector',
        ),
    ]
