# Generated by Django 4.1.7 on 2023-03-24 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_alter_sector_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='isActive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='isDefault',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolioScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
