# Generated by Django 4.1.7 on 2023-03-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_portfolio_createdat_alter_portfolio_isactive_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='Portfolio',
        ),
        migrations.AlterModelTable(
            name='userportfoliostock',
            table='UserPortfolioStock',
        ),
    ]
