# Generated by Django 4.1.7 on 2023-04-18 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0005_alter_portfolio_table_alter_userportfoliostock_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advise', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=10)),
                ('recompdate', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviser', to=settings.AUTH_USER_MODEL)),
                ('rstocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stocks')),
                ('usser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advise',
            },
        ),
    ]
